# Aligned with algorithms/MAPPO/config/mappo_cnn_cleanup.yaml
"LR_ACTOR": 0.001
"LR_CRITIC": 0.001
"LR_CORRECTION": 1.0
"CORRECTIONS": True
"NUM_ENVS": 4
"NUM_STEPS": 100
"TOTAL_TIMESTEPS": 1e8
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "clean_up"
"ENV_KWARGS":
  "num_agents": 7
  "num_inner_steps": 1000
  "shared_rewards": True
  "cnn": True
  "jit": True

"SEED": 30
"NUM_SEEDS": 1
"TUNE": False
"GIF_NUM_FRAMES": 250

# WandB Params
"ENTITY": ""
"PROJECT": "socialjax"
"WANDB_MODE": "online"
"WANDB_TAGS":
  - COMMON_REWARD
