# Aligned with algorithms/MAPPO/config/mappo_cnn_harvest_common.yaml
"LR_ACTOR": 0.0005
"LR_CRITIC": 0.0005
"LR_INCENTIVE": 0.0005
"NUM_ENVS": 5
"NUM_STEPS": 100
"TOTAL_TIMESTEPS": 1e9
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "harvest_common_open"
"ENV_KWARGS":
  "num_agents": 7
  "num_inner_steps": 1000
  "shared_rewards": True
  "cnn": True
  "jit": True

# LIO-specific
"R_MULTIPLIER": 2.0
"REG": "l1"
"REG_COEFF": 0.001

"SEED": 30
"NUM_SEEDS": 1
"TUNE": False
"GIF_NUM_FRAMES": 250

# WandB Params
"ENTITY": ""
"PROJECT": "socialjax_mappo"
"WANDB_MODE": "online"
"WANDB_TAGS":
  - COMMON_REWARD
